name: Build with Stack
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc-ver: [8.6.5, 8.4.4, 8.2.2]
      fail-fast: false
    env:
      ARGS: "--stack-yaml stack-${{ matrix.ghc-ver }}.yaml --no-terminal --system-ghc"

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: haskell-setup
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        enable-stack: true

    - name: Install the brotli library (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install libbrotli-dev -qq

    - name: Install the numa library (Ubuntu, GHC 8.4.4)
      if: ${{ runner.os == 'Linux' && matrix.ghc-ver == '8.4.4' }}
      run: |
        sudo apt-get install libnuma-dev -qq

    - name: Set environment variables based on Haskell setup
      shell: bash
      run: |
        export STACK_VER=$(stack --numeric-version)
        echo "STACK_VER=${STACK_VER}" >> ${GITHUB_ENV}

    - uses: actions/cache@v2
      name: Cache dependencies
      id: cache
      with:
        path: ${{ steps.haskell-setup.outputs.stack-root }}
        # A unique cache is used for each stack.yaml.
        key: ${{ runner.os }}-stack-${{ env.STACK_VER }}-${{ hashFiles(format('stack-{0}.yaml', matrix.ghc-ver)) }}

    - name: Build hackage-cli
      run: |
        stack build ${ARGS}

    - name: Test hackage-cli
      run: |
        stack test ${ARGS}
